# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 13:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('text', models.CharField(max_length=160)),
                ('deadline', models.DateField()),
                ('progress', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
